services:
  database:
    image: mysql:8.0
    container_name: employee_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - employee_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: employee_backend
    restart: on-failure

    ports:
      - "8081:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/employee_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      


    depends_on:
      database:
        condition: service_healthy

    networks:
      - employee_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: employee_frontend
    restart: unless-stopped

    ports:
      - "4200:80"

    depends_on:
      - backend

    networks:
      - employee_network

networks:
  employee_network:
    driver: bridge

volumes:
  mysql_data: