name: Deploy Frontend to GH Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy.yml'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install and Build 🔧
        run: |
          cd frontend
          npm install
          # Note: Replace 'employee-management-system' with your actual repo name if it differs
          npm run build -- --base-href /employee-management-system/
          cp dist/employee-management-frontend/browser/index.html dist/employee-management-frontend/browser/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist/employee-management-frontend/browser
          branch: gh-pages
