name: Deploy Frontend to GH Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          cd frontend
          npm install
          # Note: Replace 'employee-management-system' with your actual repo name if it differs
          npm run build -- --base-href /employee-management-system/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist/frontend/browser
          branch: gh-pages
